### ISSUE TITLE
Getting testnet BNB in bulk

### ISSUE THREAD

**Issue by lucas-janon** [bnb-chain/bsc-ecosystem#51]
Hi @guagualvcha! Opening an issue here because I didn't find a better place.

We're building a cross-chain protocol that relies on liquid pools on BSC and other chains.
To create the pool and test the protocol properly, I'm claiming BNB on the faucet every day but it's not enough for our goal.
Is there any chance to get testnet BNB in bulk?

Thank you.

**Comment by lucas-janon** [comment]
Hi @guagualvcha / @Loverush, we were able to get 10k a few months ago thanks a lot 🙏.

Right now we're needing more since we created a cross-chain app that interacts frequently with BSC Testnet, any chance to get another bulk?

Thank you!

**Comment by Malikrehman00107** [comment]
Attentive ! @lucas-janon you find anything?
